package com.example.tracker;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController
@RequestMapping("/api")
@CrossOrigin(origins = "*")
public class VaccineController {
    
    @Autowired
    private VaccineRepository vaccineRepository;
    
    @GetMapping("/vaccines")
    public ResponseEntity<List<Vaccine>> getAllVaccines() {
        List<Vaccine> vaccines = vaccineRepository.findAll();
        // Sort by ID descending (newest first)
        vaccines.sort(Comparator.comparing(Vaccine::getId).reversed());
        return ResponseEntity.ok(vaccines);
    }
    
    @GetMapping("/vaccines/{id}")
    public ResponseEntity<Vaccine> getVaccineById(@PathVariable Long id) {
        Optional<Vaccine> vaccine = vaccineRepository.findById(id);
        return vaccine.map(ResponseEntity::ok)
                     .orElseGet(() -> ResponseEntity.notFound().build());
    }
    
    @PostMapping("/vaccines")
    public ResponseEntity<Vaccine> createVaccine(@RequestBody Vaccine vaccine) {
        // ID will be auto-generated by database
        vaccine.setId(null);
        Vaccine savedVaccine = vaccineRepository.save(vaccine);
        System.out.println("✓ Created new vaccine record: " + savedVaccine.getPatientName() + " (ID: " + savedVaccine.getId() + ")");
        return ResponseEntity.ok(savedVaccine);
    }
    
    @PutMapping("/vaccines/{id}")
    public ResponseEntity<Vaccine> updateVaccine(@PathVariable Long id, @RequestBody Vaccine vaccine) {
        if (vaccineRepository.existsById(id)) {
            vaccine.setId(id);
            Vaccine updatedVaccine = vaccineRepository.save(vaccine);
            System.out.println("✓ Updated vaccine record ID: " + id);
            return ResponseEntity.ok(updatedVaccine);
        }
        return ResponseEntity.notFound().build();
    }
    
    @DeleteMapping("/vaccines/{id}")
    public ResponseEntity<Void> deleteVaccine(@PathVariable Long id) {
        if (vaccineRepository.existsById(id)) {
            vaccineRepository.deleteById(id);
            System.out.println("✓ Deleted vaccine record ID: " + id);
            return ResponseEntity.ok().build();
        }
        return ResponseEntity.notFound().build();
    }
}
